import axios from 'axios';
import { getAccessToken } from '../../utils/auth';
import { csrfService } from '../csrfService';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:7071/api/v1';

/**
 * Create axios instance with authentication and CSRF protection (SEC-004)
 * This function creates a new axios instance for each request with fresh auth token
 * and CSRF protection for state-changing requests
 */
export async function getAuthenticatedAxios() {
  const token = await getAccessToken();
  const instance = axios.create({
    baseURL: API_BASE_URL,
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });

  // Add CSRF header to state-changing requests (POST, PUT, PATCH, DELETE)
  // CSRF token is now generated by backend and set via Set-Cookie header
  // Frontend reads it from cookie and includes it in requests
  instance.interceptors.request.use((config) => {
    const method = config.method?.toLowerCase();
    if (method && ['post', 'put', 'patch', 'delete'].includes(method)) {
      // Read CSRF token from cookie (set by backend)
      const csrfToken = csrfService.getToken();

      // Only add header if token exists (backend sets it on first auth)
      // If token is missing, the backend will return 403 CSRF_COOKIE_MISSING
      if (csrfToken && config.headers) {
        config.headers[csrfService.getHeaderName()] = csrfToken;
      } else if (!csrfToken) {
        console.warn(
          '[API Client] CSRF token not found in cookie. ' +
            'This request may fail CSRF validation. ' +
            'Token should be set by backend on authentication.'
        );
      }
    }
    return config;
  });

  return instance;
}

/**
 * Get API base URL (useful for special endpoints like /health that are not under /v1)
 */
export function getApiBaseUrl(): string {
  return API_BASE_URL;
}

/**
 * Get API base URL without version prefix
 * Used for endpoints like /health that are not versioned
 */
export function getApiBaseUrlWithoutVersion(): string {
  return API_BASE_URL.replace('/v1', '');
}
